modLoader = '${minecraft.modLoader.loader}'
loaderVersion = '${minecraft.modLoader.range}'

[[mods]]
    modId = '${ExampleMod2.id}'
    version = '${ExampleMod2.version}'

    displayName = '${ExampleMod2.meta.displayName}'
    description = '${ExampleMod2.meta.description}'

[[dependencies.${ExampleMod2.id}]]
    modId = '${ExampleModLib.id}'
    mandatory = true
    versionRange = '[${ExampleModLib.version}]'
    ordering = 'NONE'
    side = 'BOTH'

[[dependencies.${ExampleMod2.id}]]
    modId = '${ExampleMod1.id}'
    mandatory = false
    versionRange = '[${ExampleMod1.version}]'
    ordering = 'AFTER'
    side = 'BOTH'

[[dependencies.${ExampleMod2.id}]]
    modId = 'forge'
    mandatory = true
    versionRange = '${minecraft.forge.range}'
    ordering = 'NONE'
    side = 'BOTH'

[[dependencies.${ExampleMod2.id}]]
    modId = 'minecraft'
    mandatory = true
    versionRange = '${minecraft.range}'
    ordering = 'NONE'
    side = 'BOTH'
